### ISSUE TITLE
[Feature request] Have an option to have screen edges as hot areas.

### ISSUE THREAD

**Issue by snakedye** [AndreasBackx/waycorner#1]
The location field should take the bottom, left, right and top variant.

**Comment by AndreasBackx** [comment]
My apologies that I didn't see this sooner (GitHub notifications were messed up).

If you have any experience with Rust, it should be relatively straightforward to add. The enum for the corner (forgot the name) just needs these extra options and then the layer surface needs to be differently sized. All of the other logic should be exactly the same. Happy to review any PRs 😊

**Comment by snakedye** [comment]
Alright I'll look into it

**Comment by jmcantrell** [comment]
@snakedye Can you provide more details on what you mean by “hot areas”?

**Comment by icxes** [comment]
I actually had the same idea in mind, and went out of my way to implement it too. It kinda works (you can specify a width and a height as well as an edge - I pretty much wanted to just be able to slam my mouse to any edge of the screen to run some arbitrary command), but for now I had to change stuff so that you can't specify corner anymore... 

I haven't written anything in rust before and don't know anything about how wayland works so it's probably awful, but I might try dropping a PR if I can make it work without breaking current configs (as well as have it work as it does now, plus the edges, of course) but that might take some time until I'm less busy. 

Either way thanks a lot for doing the heavy lifting @AndreasBackx, this tool was the missing piece for me switching to Sway on my main workstation :)

**Comment by AndreasBackx** [comment]
Hey @icxes, feel free to put up the PR. I'm not the greatest Rust programmer either so maybe I'll learn something new as well, I'll be able to give you some feedback nonetheless. Also thank you very much for the kinds words.

**Comment by AndreasBackx** [comment]
Thanks again @jhpaques for the PR! My apologies for the delay! <3
