### ISSUE TITLE
cpu usage hits 100% after a while (voidlinux)

### ISSUE THREAD

**Issue by axwnet** [AndreasBackx/waycorner#2]
regardless which programm is launched.

**Comment by AndreasBackx** [comment]
Could you share some more information of how you are using waycorner, particularly the config file would be helpful? Perhaps what you often do, like (dis)connecting displays, swapping mice, and whether you are using sway or another window manager.

Additionally, could you change how you invoke waycorner so it logs to a file? You can use the following instead of `exec waycorner`: `exec RUST_LOG="trace" waycorner &> /tmp/waycorner.log`. Then restart sway and when the problem occurs again, kill waycorner (don't restart sway as it will overwrite the log) and post the contents of `/tmp/waycorner.log` here. Then I might have some more information to debug the issue. :)

**Comment by axwnet** [comment]
I tested both in dwl and sway on void-linux.

```
[left]
# Shell command to execute when hotcorner is triggered.
command = ["bemenu-run"]  # required

# Locations of the hot corners.
# Options: top_left, top_right, bottom_right, and bottom_left.
locations = ["top_left", "bottom_left"]  # default

# Size of the hot corners in pixels.
size = 1  # default

# Timeout in milliseconds before command is triggered.
timeout_ms = 0  # default

# Optional output config to specify what output to use.
[left.output]
# Regex to match output descriptions on.
# Regex engine is similar to RE2: https://github.com/rust-lang/regex
#
# Use `swaymsg -t get_outputs` to get a list of outputs in the format:
# Output ${NAME} '${DESCRIPTION}'
description = ""  # default, empty means all outputs
```

I changed the config file, and now it seems to work.

```
[top_left]
# Shell command to execute when hotcorner is triggered.
command = ["bemenu-run"]  # required

# Locations of the hot corners.
# Options: top_left, top_right, bottom_right, and bottom_left.
locations = ["top_left"]  # default

# Size of the hot corners in pixels.
size = 1

# Timeout in milliseconds before command is triggered.
timeout_ms = 20
```

**Comment by axwnet** [comment]
Tested: 
`timeout_ms = 0` causes it

**Comment by AndreasBackx** [comment]
Thanks for reporting! A new version should automatically be rolled out to AUR. 😀
